name: Runner

on:
  push:
    branches: [main]
    paths:
      - "loadrunner/**"
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.2.2
        with:
          # List of tags
          tags: |
            jsteinmann/load-tests/runner:latest
            jsteinmann/load-tests/runner:${{ github.sha }}
          push: true
